### ISSUE TITLE
Backport to branch(3.7) failed: Fix broken links for the "Getting Started" doc

### ISSUE THREAD

**Issue by feeblefakie** [scalar-labs/scalardb#1010]
Backport of https://github.com/scalar-labs/scalardb/pull/1004 to branch(3.7) failed

**Comment by brfrn169** [comment]
@josh-wong Creating a PR for branch(3.7) failed. Can you please create it manually?

**Comment by josh-wong** [comment]
Will do👍

**Comment by brfrn169** [comment]
@josh-wong created https://github.com/scalar-labs/scalardb/pull/1014. Closing this issue.
