### ISSUE TITLE
Backport to branch(3.6) failed: Fix broken links for the "Getting Started" doc

### ISSUE THREAD

**Issue by feeblefakie** [scalar-labs/scalardb#1011]
Backport of https://github.com/scalar-labs/scalardb/pull/1004 to branch(3.6) failed

**Comment by brfrn169** [comment]
@josh-wong Creating a PR for branch(3.6) failed. Can you please create it manually?

And maybe you also want to create a PR for branch(3.5), right? If so, please create it manually as well. Thanks.

**Comment by josh-wong** [comment]
@brfrn169 Will do👍

**Comment by brfrn169** [comment]
@josh-wong created https://github.com/scalar-labs/scalardb/pull/1015. Closing this issue.
