### ISSUE TITLE
Backport to branch(3.9) failed: Revise the "Add ScalarDB to Your Build" doc

### ISSUE THREAD

**Issue by feeblefakie** [scalar-labs/scalardb#1039]
Backport of https://github.com/scalar-labs/scalardb/pull/1028 to branch(3.9) failed

**Comment by brfrn169** [comment]
@josh-wong Backporting to branch(3.9) failed. Can you please create a PR for it manually when you have time?

**Comment by josh-wong** [comment]
Backported in different PR: https://github.com/scalar-labs/scalardb/pull/1048
