### ISSUE TITLE
ScalarDB prints ? instead of values 

### ISSUE THREAD

**Issue by manuchadha1979** [scalar-labs/scalardb#127]
**Describe the bug**
In log traces, Scalardb prints ? character instead of values. Eg.

 query to prepare : [UPDATE codingjedi.partitions_of_a_tag SET tx_id=?,tx_state=?,tx_prepared_at=?,partition_info=?,before_tx_prepared_at=?,before_tx_id=?,before_tx_state=?,before_tx_committed_at=?,before_tx_version=?,before_partition_info=?,tx_version=? WHERE tag=? IF tx_version=? AND tx_id=?;].

**To Reproduce**
Increase tracing level to highest and do Put operation

**Expected behavior**
The values should be printed

**Desktop (please complete the following information):**
Windows

**Comment by feeblefakie** [comment]
That's DataStax java driver's behavior so please create an issue here. https://github.com/datastax/java-driver
