### ISSUE TITLE
Scan after put doesn't return the written value, nor raise an error for EXTRA_READ

### ISSUE THREAD

**Issue by Yonezawa-T2** [scalar-labs/scalardb#150]
**Describe the bug**

With `EXTRA_READ` strategy, scanning values after putting values doesn't return the written value, nor results in an error.

**To Reproduce**

Initial state: empty

1. Begin a transaction.
1. Read a value at `key05` (returns empty).
2. Put a value `1` at `key05`.
3. Scan from `key01` to `key10`.
4. Commit the transaction.

**Expected behavior**

The scan returns a value `1`, or the commit results in an error.

**Actual behavior**

The scan returns empty result and the commit succeeds.

**Additional context**

Linux and Cassandra 3 on Docker.

**Possible fixes**

- Checking the write set and the delete set when scanning a range and returning the written value. Since the write set contains partial records, the written value must be merged into scanned value, if exists.
- Raising an error on commit or scan if the write set is not empty, like `EXTRA_WRITE` strategy, or if keys in the write set overlap the scanned range.

**Comment by feeblefakie** [comment]
@Yonezawa-T2 Thank you!
I updated the code to make it throw an exception if a scan range overlaps with a write-set.

**Comment by feeblefakie** [comment]
Fixed in #151.
