### ISSUE TITLE
Backport to branch(3.8) failed: Fix a build error of docs/getting-started

### ISSUE THREAD

**Issue by feeblefakie** [scalar-labs/scalardb#1869]
Backport of https://github.com/scalar-labs/scalardb/pull/1852 to branch(3.8) failed

**Comment by brfrn169** [comment]
@komamitsu Could you please handle this issue when you have time? 🙇

**Comment by komamitsu** [comment]
@brfrn169 Oops. Sorry, I missed it. Will do

**Comment by komamitsu** [comment]
[Done!](https://github.com/scalar-labs/scalardb/pull/1902)
