### ISSUE TITLE
transaction.commit() unexpectedly succeeded without clustering keys

### ISSUE THREAD

**Issue by yito88** [scalar-labs/scalardb#25]
A record was committed unexpectedly by the `Put` has a clustering key as a value.
This commit should fail because the Cassandra driver throws `InvalidQueryException`.

This issue happens when a record is an initial record for the primary key.
The put for insertion isn't checked if the `Put` has the correct keys in the driver.
When the insertion succeeds, the preparation phase of the transaction also succeeds.

The commit of the transaction for the record fails because of the lack of clustering keys.
But it is eventual committed because this commit phase is after the state updating.

**Comment by feeblefakie** [comment]
It should be fixed with https://github.com/scalar-labs/scalardb/commit/46e3562223409688307c8693344b4b5bdab63e83 .
Please reopen the issue if you still have the issue.
