### ISSUE TITLE
[Question]How to use ScalarDB in a way that data is stored in DynamoDBLocal?

### ISSUE THREAD

**Issue by scalar-kato** [scalar-labs/scalardb#252]
**Is your feature request related to the problem? Please explain**.

I believe ScalarDB supports DynamoDB since Version 3.0.0. I would like to use ScalarDB in the form of storing data in [DynamoDBLocal](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.html). The reason for this is that when we develop as a team, we prepare test data to validate the source code implemented in the local environment, and we want to develop without mixing in test data used by other engineers on the same team while working. We are also concerned that if we store the test data during development in the local environment in AWS DynamoDB, we will incur AWS DynamoDB costs for that.
Is there any way to use ScalarDB with DynamoDBLocal?

**Please describe the solution you want**.

I would like to use ScalarDB in the form of storing data in DynamoDBLocal.

**Describe the alternatives you have considered**.

If there is no way to use ScalarDB in the form of storing data in DynamoDBLocal, I would consider the following methods

If there is no way to use ScalarDB in the form of storing data in DynamoDBLocal, I would consider the following: - Unify the AWS DynamoDB tables used for development in the local environment with the team.
Assign an AWS DynamoDB table to each engineer.

I would like to avoid both of these methods, however, because they incur AWS DynamoDB costs.

**Additional context**.

**Comment by feeblefakie** [comment]
@scalar-kato Thank you for asking. But please ask questions in [stackoverflow](https://stackoverflow.com/questions/tagged/scalardb). Here is the place for reporting bugs.
