### ISSUE TITLE
Add automated integration test to check server's backward compatiblity

### ISSUE THREAD

**Issue by laysakura** [scalar-labs/scalardb#768]
**Is your feature request related to a problem? Please describe.**
Not a major problem but currently the test is done manually: https://github.com/scalar-labs/scalardb/pull/760#issuecomment-1360682565

**Describe the solution you'd like**
Add a test called from GitHub Actions.

**Describe alternatives you've considered**
Continue manual testing.

**Additional context**

**Comment by brfrn169** [comment]
ScalarDB Server has been deprecated, so closing this issue.
