### ISSUE TITLE
Backport to branch(3.7) failed: Should call abort() when aborting transaction in transaction wrapper classes

### ISSUE THREAD

**Issue by feeblefakie** [scalar-labs/scalardb#921]
Backport of https://github.com/scalar-labs/scalardb/pull/919 to branch(3.7) failed

**Comment by komamitsu** [comment]
https://github.com/scalar-labs/scalardb/pull/922 and https://github.com/scalar-labs/scalardb/pull/923 also failed.

**Comment by brfrn169** [comment]
I have pushed the change of https://github.com/scalar-labs/scalardb/pull/919 to the `3.7`, `3.8`, and `3.9` branches.
