### ISSUE TITLE
Backport to branch(3.9) failed: Improve some  expressions of Selection Operators

### ISSUE THREAD

**Issue by feeblefakie** [scalar-labs/scalardb#926]
Backport of https://github.com/scalar-labs/scalardb/pull/920 to branch(3.9) failed

**Comment by brfrn169** [comment]
@komamitsu I'll handle this.

**Comment by brfrn169** [comment]
Back-ported the change of https://github.com/scalar-labs/scalardb/pull/920 to the branches.

**Comment by komamitsu** [comment]
@brfrn169 Thanks!

**Comment by komamitsu** [comment]
I see. The cherry-pick expected the original code contains `.add("conjunctions", conjunctions)`, but the release version branches didn't contain it. Difficult...

**Comment by brfrn169** [comment]
Yeah. In this case, it's difficult to merge such a change automatically, so we need to merge it manually.
